<a href="https://colab.research.google.com/github/Omdena-Bhutan/starter-assignment-dechendorji2025/blob/main/numpyAss_W_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [89]:

import numpy as np
a = np.array([0,1,2,3,4])
a
# change the array number
a [0] = 200
a

# slicing the numpy array # index is always n-1
d = a[1:4]
d
# slice the array
a[1:3] = 300, 400
a
# changing second element to value 20
a[1] = 20
a
#steps slicing
arr = np.array ([1,2,3,4,5,6,7])
print(arr[1:5:2])
#use : before or : after
print(arr[:5])
print(arr[4: ])
#assigning value with list
select = [0,2,3,4]
select
# using list as argument in the brackets
d = a[select]
d
# assigning specific element to a new value like 4 to 10000
a[select] = 10000
a
#other attributes
b = np.array ([1,2,3,4,5,6])
b
# get the size of numpy array
a.size
# how to know the dimensions of the numpy array
a.ndim
#find the size, dimension and shape of the given array b
b = np.array([10,20,30,40,50,60,70])
b.shape
b.ndim
b.size
#numpy statistical functions
c = np.array([-10,201,43,94,502])
max_c = c.max()
max_c
min_c = c.min()
min_c
sum =(max_c + min_c)
sum
# performing addition operation on the given numpy arrays
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
sum = arr1+arr2
sum
# performing substraction using two arrays
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
c = np.subtract(arr1, arr2)
c
# array multiply
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3,4, 5])
d = np.multiply(arr1, arr2)
d
#array division operatio
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
e = np.divide(arr1, arr2)
e
# dot operation of arrays
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])
f = np.dot (arr1, arr2)
f
#adding constant 1 to each element in the array
arr = np.array([1, 2, 3,-1])
arr = arr + 1
arr
# adding constant 5 to each element
arr = arr + 5

# Numpy linespace
g = np.linspace(5, 4, num = 6)
g
# Quiz on 1 D numpy array
h = np.array([0, 1])
i = np.array([0, 1])
h - i
# numpy mulitiply
j =np.array([1, 2, 3, 4, 5])
k =np.array([1, 0, 1, 0, 1])
l = j * k

# multiply the numpy array with z with -2
z = np. array([2, 4])
y = -2*z
y
# how to use plotvec
# imoprt the libraries
import time
import sys
import numpy as np
import matplotlib.pyplot as plt
def plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width = 0.05, color = 'r', head_length = 0.1)
    plt.text(*(a+0.1),'a')
    ax.arrow(0, 0 *b, head_with=0.05, color ='b', head_length=0.1)
    plt.text (*(b + 0.1, 'b'))
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)
    a = np.array([-1, 1])
    b = np.array([-1, 1])
    plotvec2(a, b)
    print("The dot product is", np.dot(a, b))
    a = np.array([1, 0])
    b = np. array([0, 1])
    plotvec2(a, b)
    print ('The DOT PRODUCT IS',np.dot(a, b))




[2 4]
[1 2 3 4 5]
[5 6 7]


In [ ]:

import numpy as np
a = np.array([0,1,2,3,4])
a
# change the array number
a [0] = 200
a

# slicing the numpy array # index is always n-1
d = a[1:4]
d
# slice the array
a[1:3] = 300, 400
a
# changing second element to value 20
a[1] = 20
a
#steps slicing
arr = np.array ([1,2,3,4,5,6,7])
print(arr[1:5:2])
#use : before or : after
print(arr[:5])
print(arr[4: ])
#assigning value with list
select = [0,2,3,4]
select
# using list as argument in the brackets
d = a[select]
d
# assigning specific element to a new value like 4 to 10000
a[select] = 10000
a
#other attributes
b = np.array ([1,2,3,4,5,6])
b
# get the size of numpy array
a.size
# how to know the dimensions of the numpy array
a.ndim
#find the size, dimension and shape of the given array b
b = np.array([10,20,30,40,50,60,70])
b.shape
b.ndim
b.size
#numpy statistical functions
c = np.array([-10,201,43,94,502])
max_c = c.max()
max_c
min_c = c.min()
min_c
sum =(max_c + min_c)
sum
# performing addition operation on the given numpy arrays
arr1 = np.array([10,11,12,13,14,15])
arr2 = np.array([20,21,22,23,24,25])
sum = arr1+arr2
sum
# performing substraction using two arrays
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
c = np.subtract(arr1, arr2)
c
# array multiply
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 1, 2, 3,4, 5])
d = np.multiply(arr1, arr2)
d
#array division operatio
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])
e = np.divide(arr1, arr2)
e
# dot operation of arrays
arr1 = np.array([3, 5])
arr2 = np.array([2, 4])
f = np.dot (arr1, arr2)
f
#adding constant 1 to each element in the array
arr = np.array([1, 2, 3,-1])
arr = arr + 1
arr
# adding constant 5 to each element
arr = arr + 5

# Numpy linespace
g = np.linspace(5, 4, num = 6)
g
# Quiz on 1 D numpy array
h = np.array([0, 1])
i = np.array([0, 1])
h - i
# numpy mulitiply
j =np.array([1, 2, 3, 4, 5])
k =np.array([1, 0, 1, 0, 1])
l = j * k

# multiply the numpy array with z with -2
z = np. array([2, 4])
y = -2*z
y
# how to use plotvec
# imoprt the libraries
import time
import sys
import numpy as np
import matplotlib.pyplot as plt
def plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width = 0.05, color = 'r', head_length = 0.1)
    plt.text(*(a+0.1),'a')
    ax.arrow(0, 0 *b, head_with=0.05, color ='b', head_length=0.1)
    plt.text (*(b + 0.1, 'b'))
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)
    a = np.array([-1, 1])
    b = np.array([-1, 1])
    plotvec2(a, b)
    print("The dot product is", np.dot(a, b))
    a = np.array([1, 0])
    b = np. array([0, 1])
    plotvec2(a, b)
    print ('The DOT PRODUCT IS',np.dot(a, b))




[2 4]
[1 2 3 4 5]
[5 6 7]


In [105]:

# how to use plotvec
# imoprt the libraries
import time
import sys
import numpy as np
import matplotlib.pyplot as plt
def plotvec2(a,b):
    ax = plt.axes()
    ax.arrow(0, 0, *a, head_width = 0.05, color = 'r', head_length = 0.1)
    plt.text(*(a+0.1),'a')
    ax.arrow(0, 0 *b, head_with=0.05, color ='b', head_length=0.1)
    plt.text (*(b + 0.1, 'b'))
    plt.ylim(-2, 2)
    plt.xlim(-2, 2)
    a = np.array([-1, 1])
    b = np.array([-1, 1])
    plotvec2(a, b)
    print("The dot product is", np.dot(a, b))
    a = np.array([1, 0])
    b = np. array([0, 1])
    plotvec2(a, b)
    print ('The DOT PRODUCT IS',np.dot(a, b))




In [109]:
#multi operation of arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([8, 9, 10])
add = np.add(arr1, arr2)
add
arr3 = np.subtract(arr1, arr2)
arr3
arr4 = np.multiply(arr1, arr2)
arr4
arr5 = np.divide(arr1, arr2)
arr5
arr6 = np.dot(arr1, arr2)
arr6


np.int64(56)

In [117]:
# how to sort even and odd number from array
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
even_arr1 = arr1[1:5:2]
even_arr1
odd_arr1 = arr1[0:5:2]
odd_arr1
even_arr2 = arr2[0:5:2]
even_arr2
odd_arr2 =arr2[1:5:2]
odd_arr2
print(" Congratulations, you have completed your first lesspn and hands_on lan in Python")

 Congratulations, you have completed your first lesspn and hands_on lan in Python
